version: '3.8'

services:
  app:
    container_name: employee-app
    image: employee-app
    build:
      context: .
      target: web-server
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
